name: job_timer
description: Job Timer controlador de Tempo de Trabalho.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # Modular
  flutter_modular: ^5.0.2
  modular_bloc_bind: ^1.0.1
  asuka:
    git:
      url: https://github.com/Flutterando/asuka.git
      ref: 82e0b98497d19d42e974d8252b31d13fde8e4ffb
  # Moduelar End

  # General
  validatorless: ^1.2.1
  fl_chart: ^0.51.0
  # General

  # Fireabse
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^5.3.2
  # Firebase End

  #Bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  # Bloc End

  # Isar (NoSQL)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Path
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  isar_generator: ^3.1.0+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf